name: Stress Level CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t batturashmitha/stress-level-app:latest .

      - name: Test Docker image
        run: |
          docker run -d -p 5001:5001 --name stress-app batturashmitha/stress-level-app:latest
          sleep 10
          curl http://localhost:5001

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push batturashmitha/stress-level-app:latest
          docker run -d -p 5001:5001 --name stress-app stress-level-app
          sleep 10
          curl http://localhost:5001
